"""use mapped types, replace age by date of birth

Revision ID: 8e86c2c059f8
Revises: 8c84f329844b
Create Date: 2025-01-13 16:45:51.610115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e86c2c059f8'
down_revision: Union[str, None] = '8c84f329844b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'children',
        sa.Column(
            'date_of_birth',
            sa.Date(),
            nullable=False,
            server_default='2000-01-01'
        )
    )
    op.drop_column('children', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('children', sa.Column('age', sa.INTEGER(), nullable=False))
    op.drop_column('children', 'date_of_birth')
    # ### end Alembic commands ###
